#!/usr/bin/env bash -x

oauth=$(cat oauth) 
pw=$(cat pw) 
export oauth
export pw

expect << 'EOS'
    set timeout -1
    spawn otpclient-cli show -a $::env(oauth)
    expect "Type the DB decryption password:"
    send -- "$::env(pw)\r"
    expect oef;
    exit 0
EOS


