#!/usr/bin/env bash

uname=$(uname)
tool=$(which oathtool)

if [ "$uname" == "Darwin" ]; then
    tool="/opt/local/bin/oathtool"
fi

counter=$(cat ./hotp-counter)

hotp_secret=$(pass show redhat.com/hotp-secret | tr -d '\n')

if [ "$hotp_secret" == "" ]; then
   hotp_secret=$(cat ./hotp-secret)
fi

if [ "$hotp_secret" != "" ]; then
    $tool -b -c $counter $hotp_secret
    counter=$((counter+1))
    echo $counter > ./hotp-counter
    exit 0
fi

exit 1
