#!/usr/bin/env bash

uname=$(uname)
tool=$(which oathtool)

if [ "$uname" == "Darwin" ]; then
    tool="/opt/local/bin/oathtool"
fi

counter=$(cat ./hotp-counter)
$tool -b -c $counter $(cat ./hotp-secret)
counter=$((counter+1))
echo $counter > ./hotp-counter
