#!/usr/bin/env python3


import argparse
import platform
import requests
import subprocess
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.support import expected_conditions as EC
import traceback
import time

chrome_driver_dir = "/usr/local/bin/"
chrome_driver_location = chrome_driver_dir + "/chromedriver"
profile_location = "/home/daoneill/.config/google-chrome-beta/Profile 1"

def get_token_string():
    my_parser = argparse.ArgumentParser(description='login to redhat osd')
    my_parser.add_argument('env', metavar='env', type=str, help='the env to get a token')
    my_parser.add_argument('-hl', '--headless', action='store_true', help='Run selenium in headless mode')
    args = my_parser.parse_args()

    url = None

    if args.env == "e":
        url = "https://oauth-openshift.apps.crc-eph.r9lp.p1.openshiftapps.com/oauth/token/request"
    elif args.env == "p":
        url = "https://oauth-openshift.apps.crcp01ue1.o9m8.p1.openshiftapps.com/oauth/token/request"
    elif args.env == "s":
        url = "https://oauth-openshift.apps.crcs02ue1.urby.p1.openshiftapps.com/oauth/token/request"
    elif args.env == "ap":
        url = "https://oauth-openshift.apps.appsrep05ue1.zqxk.p1.openshiftapps.com/oauth/token/request"
    elif args.env == "cp":
        url = "https://oauth-openshift.apps.appsres03ue1.5nvu.p1.openshiftapps.com/oauth/token/request"
    else:
        url = None

    options = Options()
    options.binary_location = "/opt/google/chrome-beta/google-chrome-beta"
    options.add_argument("--user-data-dir=" + profile_location)
    if args.headless:
        options.add_argument('--headless')
    service = Service(chrome_driver_location)

    # Initialize the WebDriver
    driver = webdriver.Chrome(service=service, options=options)

    # Navigate to the URL
    driver.get(url)

    # Wait until the URL has changed
    wait = WebDriverWait(driver, 20)
    wait.until(lambda driver: driver.current_url != url)

    # Wait for the presence of the element
    element_present = EC.presence_of_element_located((By.XPATH, '//a'))
    WebDriverWait(driver, 20).until(element_present)

    # Now find the element and click it
    link = driver.find_element(By.XPATH, '//a')
    link.click()

    Button=''
    while not Button:
        try:
            Button = driver.find_element(By.XPATH,'//button')
            Button.click()
            time.sleep(0.5)
        except:
            continue

    Pre=''
    while not Pre:
        try:
            Pre = driver.find_element(By.XPATH,'//pre').text
            Pre.replace("('","").replace("')","").replace("'","").replace("\n","")
            time.sleep(0.5)
        except:
            continue

    parts = Pre.split(" ")
    login_process = subprocess.Popen(parts, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, _ = login_process.communicate()

    print(Pre)
    print(stdout.decode("UTF-8"))

    driver.close()

if __name__ == "__main__":
    get_token_string()
