#!/usr/bin/env bash

# Wait for the service on port 8009 to be up
while ! nc -z localhost 8009; do
  echo "Waiting for service on port 8009 to be up..."
  sleep 2  # Wait 2 seconds before retrying
done

vpn=$(pass show redhat.com/nm-uuid | tr -d '\n')
response=$(curl -s "http://localhost:8009/get_creds?context=associate&headless=false")
creds=$(echo "$response" | tr -d '"' | tr -d '\n')  # Remove quotes from the response
pw=$(echo "$creds" | cut -d',' -f2)

echo "vpn.secrets.password:$pw" | sudo tee /tmp/vpnpw > /dev/null
sudo cat /tmp/vpnpw
sudo nmcli con up uuid "$vpn" passwd-file /tmp/vpnpw
sudo rm -f /tmp/vpnpw