---
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions: write-all

jobs:
  cicd:
    secrets: inherit
    uses: dmzoneill/dmzoneill/.github/workflows/dispatch.yaml@main
    with:
      basic: "true"
      VALIDATE_JSCPD: "false"
      VALIDATE_PYTHON_MYPY: "false"
      VALIDATE_PYTHON_PYLINT: "false"
      VALIDATE_DOCKERFILE_HADOLINT: "false"
      VALIDATE_JAVASCRIPT_STANDARD: "false"
      VALIDATE_MARKDOWN: "false"
